DROP TABLE CART_ITEMS;
DROP TABLE DETAIL;
DROP TABLE INQUIRY_COMMENT;
DROP TABLE INQUIRY_BOARD;
DROP TABLE POPUP;
DROP TABLE PROMOTION_COMMENT;
DROP TABLE PROMOTION_LIKES;
DROP TABLE PROMOTION_BOARD;
DROP TABLE PUBLICITY;
DROP TABLE REVIEWS_COMMENTS;
DROP TABLE REVIEWS_BOARD;
DROP TABLE REVIEWS_LIKES;
DROP TABLE GOODS;
DROP TABLE GOODSDETAIL;
DROP TABLE EVENT_BOARD;
DROP TABLE USERS;
DROP TABLE INQUIRY_BOARD;
DROP TABLE INQUIRY_LIKES;
----------------------------    테이블 드랍 ------------------------------------
DROP SEQUENCE EVENT_EVENT_VIEWCOUNT;
DROP SEQUENCE GOODS_SEQ;
DROP SEQUENCE INQUIRY_BOARD_SEQ;
DROP SEQUENCE INQUIRY_COMMENT_SEQ;
DROP SEQUENCE POPUP_POPUP_LIKE;
DROP SEQUENCE POPUP_POPUP_VIEWCOUNT;
DROP SEQUENCE PROMOTION_BOARD_SEQ;
DROP SEQUENCE PROMOTION_COMMENT_SEQ;
DROP SEQUENCE PROMOTION_LIKES_SEQ;
DROP SEQUENCE SEQ_LIKE_ID;
DROP SEQUENCE SEQ_REVIEW_COMMENT;
DROP SEQUENCE SEQ_REVIEW_NUM;
DROP SEQUENCE USERS_NUM;
DROP SEQUENCE CART_ID_SEQ;
DROP SEQUENCE INQUIRY_LIKES_SEQ;
-------------------------            시퀀스 드랍     ------------------------------------------




