--pomotion 테이블 생성
CREATE TABLE PROMOTION_BOARD (
    promotion_num NUMBER PRIMARY KEY,
    user_nick VARCHAR2(100) NOT NULL,
    promotion_title VARCHAR2(100) NOT NULL,
    promotion_content CLOB,
    promotion_create_date DATE DEFAULT SYSDATE NOT NULL,
    promotion_ofile VARCHAR2(200),
    promotion_sfile VARCHAR2(300),
    downcount NUMBER(5) DEFAULT 0 NOT NULL,
    visitcount NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_user_nick_promotion FOREIGN KEY(user_nick) REFERENCES USERS(user_nick)
    ON DELETE CASCADE
);

--  ptomotion테이블시퀀스 생성
create sequence promotion_board_seq
increment by 1 
start with 1    
minvalue 1     
nomaxvalue      
nocycle        
nocache;        


-- promotion 댓글 생성
CREATE TABLE promotion_COMMENT (
    promotion_comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_num NUMBER NOT NULL,
    user_nick VARCHAR2(100) NOT NULL,
    promotion_comment_content VARCHAR2(1000) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_promotion_num FOREIGN KEY (promotion_num) REFERENCES promotion_BOARD(promotion_num)
    ON DELETE CASCADE,
    CONSTRAINT fk_user_nick_comment_promotion FOREIGN KEY (user_nick) REFERENCES USERS(user_nick)
    ON DELETE CASCADE
);

--promotion 댓글 시퀀스생성
CREATE SEQUENCE promotion_comment_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

--promotion 좋아요 테이블 생성
CREATE TABLE PROMOTION_LIKES (
    like_id NUMBER PRIMARY KEY,
    promotion_num NUMBER NOT NULL,
    user_nick VARCHAR2(100) NOT NULL,
    like_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_like_promotion FOREIGN KEY(promotion_num) REFERENCES PROMOTION_BOARD(promotion_num)
    ON DELETE CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY(user_nick) REFERENCES USERS(user_nick)
    ON DELETE CASCADE
);

-- promotion 좋아요 시퀀스 생성
CREATE SEQUENCE promotion_likes_seq
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;




